web:
  image: gigatec/ubuntu-16.04-php(5.6|7.0)-(dev|prod)
  container_name: <project>.dev
  environment:
    - DOCKER_SYSTEM=<wordpress|magento|plain|>
  volumes:
    - ./:/vagrant
  expose:
    - 80
